name = "handover-cloud-api"
main = "src/index.js"
compatibility_date = "2026-04-05"
workers_dev = true

[vars]
ALLOWED_USERS = "caesarmetro"

[[d1_databases]]
binding = "DB"
database_name = "handover-db"
database_id = "a83eb4bf-2875-4035-a694-fadd28228ef8"
